# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: "Learning IBM Business Automation Open Edition"
site_description: "A set of demos and guided-exercises about business automation with Apache KIE projects"
site_author: "IBM Technical Sales"
repo_url: https://github.com/ibm/bamoe-university
edit_uri: ""
extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: en
  - markdownextradata: {}
  - awesome-pages: #https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
      collapse_single_pages: true
  - enumerate-headings: # https://github.com/timvink/mkdocs-enumerate-headings-plugin
      toc_depth: 0
      strict: true
      increment_across_pages: true
      exclude:
        - index.md
        - more.md
        - README.md
  - git-revision-date-localized:
      type: iso_date
  - with-pdf:
         author: Barry Lulas at IBM - barry.lulas@ibm.com

extra:
  product: 
    name: "IBM Business Automation Open Edition 9.2.x"
    legacy: "IBM Business Automation Open Edition 8.0"
    short: "BAMOE"
    dm: "Decision Manager Open Edition"
    pam: "Process Automation Manager Open Edition"
    version: "9.2.0"
    versionLegacy: "8.0.7"
    maven: "Red Hat Maven General Access Repository"
    legacymaven: "Red Hat Maven General Access Repository"
    legacygav: "7.67.2.Final-redhat-00017"
    gav: "7.67.2.Final-redhat-00017"
    kogitobom: "9.2.0-ibm-0004"
    kogitogroup: "com.ibm.bamoe"
    kogitoplugin: "2.16.7.Final"
    sandbox: "KIE Sandbox"
    canvas: "IBM Business Automation Manager Canvas"
    extended: "Extended Services"
    workspace: "quick-kogito"
    bamAdmin: "bamAdmin"
    bamPass: "ibmpam1!"
    runner: "DMN Runner"
  sandbox:
    experimental: "https://kiegroup.github.io/kogito-online-staging/kie-sandbox-accelerators/#/"
    production: "http://localhost:9090/#"
  generator: false

theme:
  name: material
  navigation_depth: 2
  locale: en
  generator: false
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
        primary: light-blue
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - toc.follow
    - navigation.top
    - search.highlight
    - search.share

markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets
  - meta
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
